### ISSUE TITLE
Make Readme.md

### ISSUE THREAD

**Issue by 16min99** [prgrms-web-devcourse/Team_17TOP_Film_BE#85]
https://www.notion.so/backend-devcourse/Readme-md-9a212f72ac544d4db3b742bee8191ac0

**Comment by jungeu1509** [comment]
![ERD_Film](https://user-images.githubusercontent.com/52902010/146955622-70818c03-68ca-4827-a778-ea436136e681.png)
![cicd](https://user-images.githubusercontent.com/52902010/146955932-c4a11bf7-444a-45aa-9b04-354e1b11d1a9.png)
![login](https://user-images.githubusercontent.com/52902010/146955940-27789345-3d0b-4946-89cf-ccbd429994e5.png)
![multimodule](https://user-images.githubusercontent.com/52902010/146955947-314a33e4-1a3d-4aff-98f7-262d5d890f2f.png)
